### PR TITLE
Improvements for Duke Nukem Forever (2011)

### PR DESCRIPTION
**Pull request by DaZombieKiller**
* DNF uses `var pointer(T)` instead of `var pointer` syntax
* `delegate<T>` fields are compiler-generated in DNF and cannot be defined in source
* `FUNC_Delegate` is `0x400000` in DNF
* `0x20000000` is `FUNC_DevExec`, it is often combined with `0x200` which gives `0x20000200`
* `0x00800000` is `CPF_Comment` and the syntax is `var T name ?("comment");`

### CODE REVIEW

**Comment by DaZombieKiller** [comment]
I wonder if it's worth implementing a class/property flag remapper like what exists for UnrealScript opcodes. Then UELib can have its own internal representation of the flags that can be safely checked, instead of needing to manually remap and handle engine-specific flags (especially for cases where the same flag happens to be stored in a different bit compared to most implementations). Any thoughts on this?

**Comment by EliotVU** [comment]
Looking good, I'll leave it open for now, as you are still pushing commits.

**Comment by EliotVU** [comment]
> I wonder if it's worth implementing a class/property flag remapper like what exists for UnrealScript opcodes. Then UELib can have its own internal representation of the flags that can be safely checked, instead of needing to manually remap and handle engine-specific flags (especially for cases where the same flag happens to be stored in a different bit compared to most implementations). Any thoughts on this?

Yes, see https://github.com/EliotVU/Unreal-Library/blob/205aeceb91cf0512849f864e1ae696d2adbf0264/src/UnrealFlags.cs#L78

I ran into this issue badly when supporting UE4 package flags, and implemented a way to abstract the unique flags for any particular game. It's only a matter of duplicating the efforts for all classes, or those with the most impact.

**Comment by DaZombieKiller** [comment]
I might attempt that in a separate PR later then, since it's probably out of scope for this one. The changes I have now should be the last of them, so feel free to merge the PR if it looks good.

If you want to mess around with the DNF compiler yourself, I have a (heavily WIP) reconstructed SDK and UCC available here: https://github.com/DaZombieKiller/DukeForeverSDK (feel free to open a discussion there if you need help setting it up, I haven't written any documentation yet).

**Comment by EliotVU** [comment]
Thanks, I'll merge this later, I plan to adjust some changes like 'IsCompilerGenerated' to generalize it for all games, e.g. generated delegates are expected to be prefixed with '__DELEGATE__'

**Pull request merged**
